### ISSUE TITLE
CollectionView.ItemsUpdatingScrollMode

### ISSUE THREAD

**Issue by juanyacovino77** [adospace/mauireactor-samples#2]
CollectionView.ItemsUpdatingScrollMode is not working for any enum case

I have workarounded with this code:

                            .OnLoaded((sender, args) =>
                            {
                                if (conversa.mensajesDeTexto.Count > 0)
                                {
                                    ContainerPage?.Dispatcher.DispatchDelayed(TimeSpan.FromMilliseconds(100), () =>
                                        ((MauiControls.CollectionView?)sender)?.ScrollTo(conversa.mensajesDeTexto[^1]));
                                }
                            })

for scrolling to the last item added, but anyways it would be nice to have it working

**Comment by adospace** [comment]
I've created a sample page and seems working for me:

https://adospace.gitbook.io/mauireactor/components/controls/collectionview/scrolling#control-scroll-position-when-new-items-are-added

Code:
https://github.com/adospace/mauireactor-samples/blob/main/Controls/CollectionViewTestApp/Pages/MainPageScrollingMode.cs

maybe it's a timing issue?

**Comment by juanyacovino77** [comment]
Well, the problem seem to be with Windows. That same sample does not work for Windows

**Comment by adospace** [comment]
ok probably is a maui itself problem
