### ISSUE TITLE
Odd Checkmark Behavior in TodoApp

### ISSUE THREAD

**Issue by nabond251** [adospace/mauireactor-samples#4]
**Describe the bug**
The TodoApp does not toggle between done and not done correctly when running on an Android device.  Behaves as expected when running on a Windows machine.

**To Reproduce**
1. Install TodoApp on a local Android device.
2. Create a task.
3. Press the task's checkbox to mark the task done.
4. Press the checkbox again to reset the task not done.

**Expected behavior**
Checkbox is cleared and strikethrough effect is removed.

**Actual behavior**
Task view cycles through all four combinations of checked/unchecked and struck through/not struck through.  Unchecked + struck through as well as checked + not struck through are invalid view states.

**Screenshots**
![Screenshot_20240216_125253 1](https://github.com/adospace/mauireactor-samples/assets/13264139/213fc2d8-705f-46c8-8d2d-a925b5824cfa)
![Screenshot_20240216_125627 1](https://github.com/adospace/mauireactor-samples/assets/13264139/57c04237-10cc-42c7-b58a-0e9ea86c4d96)

**Smartphone (please complete the following information):**
 - Device: Samsung S22
 - OS: Android 14

**Additional context**
When debugging `OnItemDoneChanged` and starting with the item unchecked/not struck through, I get the following truth table (first column is the value as read by the debugger, second and third are the resulting view state):

`bool done` | Checked? | Struck through?
-------------|------------|------------------
`true`          | Yes            | Yes
`false`         | Yes            | No
`false`         | No            | Yes
`true`          | No            | No

If I then restart the app, the task loads as done: checked and struck through.  This makes sense, as the most recent call to `OnItemDoneChanged` did have `done = true`.  From this loading done state, the truth table changes to

`bool done` | Checked? | Struck through?
-------------|------------|------------------
`false`          | No           | No
`true`           | No           | Yes
`true`           | Yes           | No
`false`          | Yes           | Yes

And reloading the app has the task load as not done: unchecked and not struck through, again as per the latest `done = false`.

Preliminary conclusions:
1. It seems the data layer is functioning correctly.  The concluding line of both the above test runs ends up with the done flag getting set in the database (as evident by the subsequent reload), even though both the checkbox and the text styling indicate the opposite.
1. With respect to the first two columns, the two tables are identical but rotated two rows.
1. With respect to the first and third columns, the two tables are reverse of each other and rotated one row.
1. With respect to the last two columns, the tables are reverse/`NOT` of each other.
1. If I take into account an additional state input - the previous state of the item in database - I get the following tables:
   Done in db before pressing checkbox? | `bool done` | Checked? | Struck through?
   -------------------------------------------|--------------|------------|------------------
   No                                                          | `true`           | Yes            | Yes
   Yes                                                          | `false`          | Yes            | No
   No                                                          | `false`          | No            | Yes
   No                                                          | `true`           | No            | No

   After reload app:

   Done in db before pressing checkbox? | `bool done` | Checked? | Struck through?
   -------------------------------------------|--------------|------------|------------------
   Yes                                                          | `false`          | No            | No
   No                                                          | `true`           | No            | Yes
   Yes                                                          | `true`           | Yes           | No
   Yes                                                          | `false`          | Yes           | Yes

   Which still aren't really complete truth tables - so either this is not the right way to consider "done in db before", or there is simply yet another variable I'm failing to consider which would complete this.  But it is worth noting that aside from the `bool done` column, as noted in 4, both tables are the complete inverse of each other.

Sorry if that is less signal than noise.  Very possible I'm overthinking this and heading in the wrong direction.  Not sure why it only seems to break on Android, suggests something is wrong with the checkbox control, but could be something is different with the reactive data too?  Anyway, interested to see what can be done here.

**Comment by adospace** [comment]
thank you for the detailed bug report, I'll look into it asap

**Comment by adospace** [comment]
Hi, I've investigated and resolved the issue (please sync the repo to see the latest version).

What was the problem: 
The .NET MAUI CheckBox works so that when the IsChanged property changes (from code or user tapping, anti-pattern IMHO) the related Changed event is fired: this causes problems when one puts the checkbox inside a CollectionView that is bound to an observable collection that receives notifications of items changing.
If I had used code like the following (i.e. use a Button instead of a CheckBox) it should've worked from the beginning:

```csharp
 VisualNode RenderItem(Todo item)
        => Grid("54", "Auto, *",
            Button(item.Done ? "x" : "")
                .OnClicked(()=> OnItemDoneChanged(item, !item.Done)),
            Label(item.Task)
                .TextDecorations(item.Done ? TextDecorations.Strikethrough : TextDecorations.None)
                .VCenter()
                .GridColumn(1));
```

Anyway, I decided to modify the ReactorData library so that one now can decide whether to update an entity "in-place" (i.e. keeping the same entity inside the container) or "replace" it with a new version of the Entity.

In the case where one has to link a `CollectionView ` to an `IQuery<>` (i.e. like in our todo sample) he must use the `Replace() `function instead of the `Update()`.

The Replace function (replacing the entity with a new entity) causes the ItemTemplate to be rendered a second time (i.e. the RenderItem function is called again with the new Entity) this time setting the CheckBox.IsChecked() property with the correct value.

**Comment by nabond251** [comment]
I can confirm that fixes the behavior on my end, thanks so much.
